### ISSUE TITLE
Feature: Support loading yaml data from string

### ISSUE THREAD

**Issue by dwapstra** [wwkimball/yamlpath#112]
**Is your feature request related to a problem? Please describe.**
For python usage, it will be useful if the get_yaml_data implementation supports loading from string instead of requiring a file.

**Describe the solution you'd like**

Prefered solution is a simply API to load the yaml data, e.g.:

```python
my_yaml_data = """
key:
  value
"""

from yamlpath import load

yaml_data = load(my_yaml_data)
```

**Describe alternatives you've considered**
Alternative, I can load directly using ruamel.yaml.

```
from ruamel.yaml import YAML

yaml_obj = YAML(typ='safe')
yaml_data = yaml_obj.load(my_yaml_data)
```

**Comment by wwkimball** [comment]
I'll add this as a convenience function.
