### ISSUE TITLE
Unexpected nodes returned for grandchild query /Locations/*/*

### ISSUE THREAD

**Issue by paxerit** [wwkimball/yamlpath#154]
## Operating System

1. Name/Distribution: Windows 10 Home
2. Version: 10.0.19043 Build 19043

## Version of Python and packages in use at the time of the issue.

1. [Distribution](https://wiki.python.org/moin/PythonDistributions): CPython (for Windows) from python.org
2. Python Version: 3.7
3. Version of yamlpath installed: 3.6.3
4. Version of ruamel.yaml installed: 0.17.10

## Minimum sample of YAML (or compatible) data necessary to trigger the issue

```yaml
---
Locations:
    United States:
        New York:
        Boston:
    Canada:
```

## Complete steps to reproduce the issue when triggered via:

1. Command-Line Tools (yaml-get, yaml-set, or eyaml-rotate-keys):  Precise command-line arguments which trigger the defect. 
2. Libraries (yamlpath.*):  Minimum amount of code necessary to trigger the defect.

#I thought that a complete unittest might be the most helpful way to demonstrate my issue. Please let me know if another format would be more helpful.

```python
import unittest
import yamlpath
from yamlpath.wrappers import ConsolePrinter
from yamlpath.common import Parsers
from yamlpath import Processor
from yamlpath.exceptions.yamlpathexception import YAMLPathException
from types import SimpleNamespace

class IssueReportTest(unittest.TestCase):
    
    def setUp(self):
        pass
    
    def tearDown(self):
        pass
    
    def test_retrieveGrandChildren_OnlyGrandChildrenAreReturned(self):
        yamlTagHierarchy = '''---
        Locations:
            United States:
                New York:
                Boston:
            Canada:
        '''
        
        logging_args = SimpleNamespace(quiet=True, verbose=False, debug=False)
        self._log = ConsolePrinter(logging_args)
        self._editor = Parsers.get_yaml_editor()
        (yaml_data, doc_loaded) = Parsers.get_yaml_data(self._editor, self._log, yamlTagHierarchy, literal=True)
        self._processor = Processor(self._log, yaml_data)
        
        nodes = list(self._processor.get_nodes("/Locations/*/*"))
        self.assertEqual(nodes[0].parentref, "New York")
        self.assertEqual(nodes[1].parentref, "Boston")
        self.assertEqual(len(nodes), 2, f"Node '{nodes[2].parentref}' should not be part of this list, or?")
```

## Expected Outcome
When I try to select a specific level of descendant nodes using child and wildcard operators I expect to receive only nodes at the requested level. For example, in the above sample I expect   "/Locations/*/*" to return "New York" and "Boston" (grandchildren of "Locations")

## Actual Outcome
If another branch of the yaml tree ends above the requested level, the query returns the last leaf on that branch. The above example returns "Canada" in addition to "New York" and "Boston", which is surprising to me as "Canada" is merely a child of "Location", while "New York" and "Boston" are grandchildren. I haven't been able to identify an easy way to distinguish the child from the grandchild nodes.

## Thank you
Thanks so much for considering this. I was thrilled to find yamlpath for a hobby project and really appreciate the library. I hope that I'm actually reporting a real issue rather than flaunting my ignorance of how the wildcard operator should work.

**Comment by wwkimball** [comment]
I've been puzzling over this one for the last few days because wildcards can be argued either way that:

- matching the first wildcard node and any children whether or not there are any
- matching only nodes that fully match the path

when _the rest of the path is just another wildcard_ are valid interpretations.

However, because there **is** more to the path -- despite it being just another wildcard -- I find myself feeling like this is a bug; that only nodes which **fully** match the path _should_ be matched.

Thank you for bringing this to my attention!

**Comment by paxerit** [comment]
Thanks for considering this.
Yes, I could also see it going both ways, which is why I wasn't 100% certain whether it was an issue. As a sanity check I thought I would see what an XPATH parser for XML would do. This [online parser](https://www.freeformatter.com/xpath-tester.html#ad-output) output only the grandchildren, so it seems that that behavior would be consistent.

Thank you very much for the thought you've given this issue.

Here is the data that I fed the online XML tool, for what it's worth:
```
<locations>
    <unitedstates>
        <newyork />
        <boston />
    </unitedstates>
    <canada />
</locations>

XPath: /locations/*/*

XPath result:
<newyork/>
<boston/>
````

**Comment by wwkimball** [comment]
Please try release version 3.6.4.  My (expanded to cover this behavior against other data constructs) pytest version of your unittest is at https://github.com/wwkimball/yamlpath/blob/master/tests/test_processor.py#L91.

Thanks again for reporting this!
