### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by mechie** [wwkimball/yamlpath#166]
Great project, thanks for the hard work on it!

**Is your feature request related to a problem? Please describe.**
Currently, importing this library forces my projects to drop Python 3.10 support, which is a bit frustrating.

As Python 3.11 nears release (October 2022), it'd be good for this library to not fall too far behind.

**Describe the solution you'd like**
Any/all issues with Python 3.10 are identified and resolved, and a new minor version of yamlpath is tagged with Python 3.10 Support.

**Describe alternatives you've considered**
Remaining on older Python versions (not a long term solution), forking yamlpath.

**Additional context**
See upcoming PR for a non-exhaustive first attempt.

**Comment by wwkimball** [comment]
I'm closing this as an issue and keeping it open as a PR where we can also converse about this improvement.
