### ISSUE TITLE
Trying to "cast" a string as a boolean value, getting int values instead

### ISSUE THREAD

**Issue by AndydeCleyre** [wwkimball/yamlpath#176]
## Operating System

1. Name/Distribution: Pop OS
2. Version: 22.04

## Version of Python and packages in use at the time of the issue.

1. [Distribution](https://wiki.python.org/moin/PythonDistributions): CPython
2. Python Version: 3.10.4
3. Version of yamlpath installed: 3.6.4
4. Version of ruamel.yaml installed: 0.17.17

## Minimum sample of YAML (or compatible) data necessary to trigger the issue

```json
{
  "People": [
    {
      "name": "Andy",
      "hasChildren": "True",
      "hasPet": "True"
    },
    {
      "name": "Fred",
      "hasChildren": "False",
      "hasPet": "False"
    }
  ]
}
```

## Complete steps to reproduce the issue:

```python
#!/usr/bin/env python3
from types import SimpleNamespace

from yamlpath import Processor as YPProcessor
from yamlpath.common import Parsers as YPParsers
from yamlpath.enums import YAMLValueFormats
from yamlpath.wrappers import ConsolePrinter as YPConsolePrinter


def str_to_bool(value: str) -> bool:
    if value.lower() in ('true', 'yes', 'y', 'on'):
        return True
    if value.lower() in ('false', 'no', 'n', 'off'):
        return False
    raise ValueError


def cast_json(json: str, bools: list[str]) -> dict | list:
    log = YPConsolePrinter(SimpleNamespace(quiet=True, verbose=False, debug=False))
    doc, success = YPParsers.get_yaml_data(YPParsers.get_yaml_editor(), log, json, literal=True)
    if not success:
        raise ValueError
    processor = YPProcessor(log, doc)

    for query_path in bools:
        matches = processor.get_nodes(query_path)
        for match in matches:
            processor.set_value(
                match.path, str_to_bool(match.node), value_format=YAMLValueFormats.BOOLEAN
            )

    return doc


if __name__ == '__main__':
    data = cast_json(
        '{"People": [{"name": "Andy", "hasChildren": "True", "hasPet": "True"}, {"name": "Fred", "hasChildren": "False", "hasPet": "False"}]}',
        ['/People/hasChildren', '/People/hasPet'],
    )
    print(f"{data=}")
```

## Expected Outcome

I can't tell if this is working as expected and I'm failing to understand the docs, or if this is unexpected.

I'm taking in json or yaml data in which all the non-list, non-hash values are strings. I'd like to end up with a `dict` equivalent wherein some items are `True` or `False`.

I expected the code above to print

```python
data=ordereddict([('People', [ordereddict([('name', 'Andy'), ('hasChildren', True), ('hasPet', True)]), ordereddict([('name', 'Fred'), ('hasChildren', False), ('hasPet', False)])])])
```

## Actual Outcome

```python
data=ordereddict([('People', [ordereddict([('name', 'Andy'), ('hasChildren', 1), ('hasPet', 1)]), ordereddict([('name', 'Fred'), ('hasChildren', 0), ('hasPet', 0)])])])
```

**Comment by wwkimball** [comment]
Based on my reading just now, there's a lot of confusion about the similarities -- and differences -- between JSON, JavaScript notation, and Python's JSON-esque notation.  You seem to have stumbled right into this.  From what I gather, the issue you've discovered is in Python's handling of the "JSON-esque" (but not valid JSON) data that you've constructed.  If the data were pure JSON, it would be a syntax error to attempt to write `True`|`False`; it would have to be quoted like `"True"|"False"`.  If the data were pure JavaScript, it could be bare tokens but would have to be lower-case like `true|false` else you'd get a syntax error.  As pure Python, you could use the bare capitalized tokens but you wouldn't be able to dump them as such; you'd get exactly what you see in your result, binary `1|0` cast to base-10 integers.

This is a limitation of JSON at the time Python's json module was written and thus, a limitation of Python's JSON dumper, and in turn a limitation of yamlpath's use of Python's json library.

Can we override this behavior to produce the exact output you expect?  Yes; monkeypatch or override [Parsers.jsonify_yaml_data](https://github.com/wwkimball/yamlpath/blob/master/yamlpath/common/parsers.py#L316) to specially handle Booleans.  However, if I override this behavior as such in the base code, yamlpath would start emitting non-portable JSON.  That would likely cause issues for other users who expect portable JSON.

I'm always open to making yamlpath better.  If you think of another (portability-safe) way to handle this, please let me know!

**Comment by AndydeCleyre** [comment]
Thanks!

I need to list out the data changes for my own understanding:

1. In the `__main__` block, the data is a `str` literal, and AFAIK valid JSON. The object has no boolean values, just strings.
2. In `cast_json`, the JSON as a `str` is used by `Parsers.get_yaml_data` to make a YAML document object. I would expect the "True" and "False" values to be YAML string values here as well. Let me see:
  ```python
  >>> type(doc)
  ruamel.yaml.comments.CommentedMap
  >>> doc['People'][0]['hasPet']
  'True'
  >>> type(_)
  ruamel.yaml.scalarstring.DoubleQuotedScalarString
  ```
3. Then we have our query matches, of type `NodeCoords`:
  ```python
  >>> match.node
  'True'
  >>> type(_)
  ruamel.yaml.scalarstring.DoubleQuotedScalarString
  ```
4. 
  ```python
  >>> str_to_bool(match.node)
  True
  >>> type(_)
  bool
  ```
5. `processor.set_value` modifies the values:
  ```python
  >>> doc['People'][0]['hasChildren']
  1
  >>> type(_)
  ruamel.yaml.scalarbool.ScalarBoolean
  ```
  Ooh, ok. Looks like a number, but still definitely boolean, still good so far.
6. Ah, this is a problem:
  ```python
  >>> from json import dumps
  >>> dumps(doc)
  '{"People": [{"name": "Andy", "hasChildren": 1, "hasPet": 1}, {"name": "Fred", "hasChildren": 0, "hasPet": 0}]}'
  ```

So, if I want to get this document object into plain old Python dict/list/string/bool/int/float objects, to feed to other serializers/structurers/unstructurers, do I want to recursively replace every `ruamel.yaml.scalarbool.ScalarBoolean` with a `bool`?

**Comment by AndydeCleyre** [comment]
Oh OK, so is `jsonify_yaml_data` invoked when `json.dums(doc)` is called?

If so, the only sticky bit is that booleans aren't portable json?

**Comment by wwkimball** [comment]
Correct; portable JSON doesn't have a Boolean data-type and that's where you're running into this surprise.

**Comment by AndydeCleyre** [comment]
Is there a certain standard/spec corresponding to portable JSON? Every spec I see defines boolean as a primitive.

**Comment by wwkimball** [comment]
https://www.json.org/json-en.html is the official JSON standard.  It mandates Boolean values must be quoted tokens in lower-case, like `"true"|"false"`.

Note that implementations of the standard differ widely (as with YAML, RegEx, and others).  For example, Python accepts bare title-case tokens.  JavaScript accepts bare lower-case tokens.  Ruby, C, Java, .Net, and so on each have their own rules.  This is where "portable JSON" comes into play.  The only guaranteed way to pass a Boolean between parsers with competing implementations is to punt to the lowest-common-delimiter:  the standard.

**Comment by wwkimball** [comment]
In hindsight, this does seem like a bad implementation of Boolean handling in either ruamel.yaml or Python's json module.  If we are sending a legitimate Boolean to the module(s) and portability -- even just between other implementations of Python -- were a primary concern, I think they should have punted to the JSON standard and had Booleans emit as `"true"|"false"`, quoted lower-case tokens.

I can be persuaded that this is a bug (not in yamlpath) that yamlpath can solve by emitting Booleans as quoted tokens.  At least then, we're following the JSON standard.

**Comment by AndydeCleyre** [comment]
Thanks so much for all this explanation. I'm still hung up on the standard. That page says:

> A *value* can be a *string* in double quotes, or a *number*, or `true` or `false` or `null`, or an *object* or an *array*.

That *sounds* like of all the types listed, only strings ought to be quoted, the rest being bare.

The other two places to look from here are the McKeeman grammar on the right, and the full PDF report for ECMA-404. I'm not confident in my understanding of that grammar format so will jump to the PDF.

The term `boolean` does not appear there, but it says:

> These are the three literal name tokens:
>   `true `U+0074 U+0072 U+0075 U+0065
>   `false`U+0066 U+0061 U+006C U+0073 U+0065
>   `null `U+006E U+0075 U+006C U+006C

That still *seems* to me like booleans and nulls ought not be quoted, but this spec lacks example documents to confirm.

If a true boolean value is to be represented as `"true"`, how can the string `true` be represented without ambiguity?

Alright I'll search for "standard JSON examples" and I find https://www.json.org/example.html which seems promising. Taking a look, the booleans are unquoted:

```json
"useJSP": false,
```
```json
"useDataStore": true,
```
As are the nulls:
```json
{"menu": {
    "header": "SVG Viewer",
    "items": [
        {"id": "Open"},
        {"id": "OpenNew", "label": "Open New"},
        null,
        {"id": "ZoomIn", "label": "Zoom In"},
        {"id": "ZoomOut", "label": "Zoom Out"},
        {"id": "OriginalView", "label": "Original View"},
        null,
        {"id": "Quality"},
        {"id": "Pause"},
        {"id": "Mute"},
        null,
        {"id": "Find", "label": "Find..."},
        {"id": "FindAgain", "label": "Find Again"},
        {"id": "Copy"},
        {"id": "CopyAgain", "label": "Copy Again"},
        {"id": "CopySVG", "label": "Copy SVG"},
        {"id": "ViewSVG", "label": "View SVG"},
        {"id": "ViewSource", "label": "View Source"},
        {"id": "SaveAs", "label": "Save As"},
        null,
        {"id": "Help"},
        {"id": "About", "label": "About Adobe CVG Viewer..."}
    ]
}}
```

**Comment by wwkimball** [comment]
Something does seem disconnected.  The cheat-sheet on the right on the JSON standard site doesn't allow for bare tokens, `true`, `false`, or `null`.  It explicitly quotes them, `"true"`, `"false"`, and `"null"`.  Yet, lower down in the description of a "value", it clearly shows the text you cited; that the same values can be bare.

Discrepancies like this likely give implementation programmers leeway to decide for themselves how to treat the values.

Here's the acid test, though:  try both in Python.  Here's what happens:

```python
>>> import json

>>> json.dumps({ "a_bool": "true" })
'{"a_bool": "true"}'

>>> json.dumps({ "a_bool": true })
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'true' is not defined

>>> json.dumps({ "a_bool": True })
'{"a_bool": true}'

>>> json.loads('{ "a_bool": true }')
{'a_bool': True}

>>> json.dumps(json.loads('{ "a_bool": true }'))
'{"a_bool": true}'

>>> json.loads(json.dumps({ "a_bool": "True" }))['a_bool'] == True
False

>>> json.loads(json.dumps({ "a_bool": "true" }))['a_bool'] == True
False

>>> json.loads(json.dumps({ "a_bool": True }))['a_bool'] == True
True

>>> json.loads(json.dumps(json.loads('{ "a_bool": "true" }')))['a_bool'] == True
False

>>> json.loads(json.dumps(json.loads('{ "a_bool": true }')))['a_bool'] == True
True
```

That's ... surprising and even disturbing.  It looks like the Python json module doesn't even recognize the quoted token as being a proper Boolean, contrary to the cheat-sheet on the JSON standard page!  I also don't see any conversions to the Integer values happening.

Okay, we now have a legitimate issue.  Python json doesn't support the stated standard quoted form.  Ruamel.yaml seems to be converting to Integers.  yamlpath will absolutely need to step in and make sense of this chaos...

Good find!  I'll take this as a ... feature'ish-bug?  Whatever we call this, yamlpath will handle accepting and emitting both forms of these value.  Or accept both forms and only emit the bare form.  I'll sort that out as I dig in.

**Comment by AndydeCleyre** [comment]
Your example session there looks completely consistent and as I would expect, as long as booleans are unquoted in JSON. I think that is the case, and you may be misinterpreting the McKeeman grammar, though I can't claim to have a handle on that.

**Comment by AndydeCleyre** [comment]
For my own use case I have moved forward by using a `cattrs` `Converter` object to transform the `ruamel.yaml` objects to their plain Python counterparts:

- `DoubleQuotedScalarString -> str`
- `ScalarBoolean -> bool`
- `ScalarInt -> int`
- `ScalarFloat -> float`
- `CommentedSeq -> list`
- `CommentedMap -> dict`

Then dumping as JSON and YAML from there.

I will link the actual code soonish; it's a new repo I haven't pushed yet.

**Comment by wwkimball** [comment]
That makes me nervous; I fear you may trigger a cascade of unexpected issues.  If I push a hotfix tonight, would that meet your timeline?

**Comment by AndydeCleyre** [comment]
Please don't rush anything for this case, which is currently a hobby project. I'm leaning in to the cattrs conversions anyway...

I'll try to figure some things out and push my first release within a day, at which point you can tell me how crazy I am.

**Comment by wwkimball** [comment]
I can't leave you hanging; I'm already working on the release.  I've fixed the code, which turned out to require a bit more code than I expected due to unexpectedly running smack into [PEP 632](https://peps.python.org/pep-0632/) with this.  I'm working on the new unit tests, right now.  I anticipate pushing out a 3.6.5 hotfix within the hour.

Besides, I need a couple of other EYAML fixes I put in this for my regular job, too.  :)

**Comment by wwkimball** [comment]
I've released version 3.6.5 which includes this fix along with some unrelated others.  Please try it out and let me know if you find any other issues!

**Comment by AndydeCleyre** [comment]
Alright, it's far from ready, but I've at least pushed an initial form of my [relevant project](https://github.com/AndydeCleyre/nestedtextto), and the JSON parts there are working. I am still "unstructuring" the data into plainer Python types before passing it to `json.dump`.

As for the yaml stuff therein, aside from my own problems getting the tests properly parameterized at the moment (nothing to do with yamlpath), I haven't figured out how to use yamlpath to properly inject a the yaml equivalents of `datetime.datetime` and `datetime.date`.

I might come back to open an issue about that once I get my yaml testing more generally sorted.

**Comment by wwkimball** [comment]
https://yaml.org/type/timestamp.html seems to be the best lead on how to format date/time data in YAML.  I don't have any explicit tests for this type of data other than when writing Python-native date/time data to JSON, a string conversion (subject to machine locale) is required because JSON itself doesn't have native date/time data types.
