### ISSUE TITLE
Missing tag for 3.7.0

### ISSUE THREAD

**Issue by mgorny** [wwkimball/yamlpath#209]
Could you please push the git tag for 3.7.0 release? We're using them for packaging on Gentoo.

**Comment by wwkimball** [comment]
Oops!  Yes, you are absolutely 100% unequivocally right!  Thanks to your reminder, I've tagged v3.7.0:  https://github.com/wwkimball/yamlpath/releases/tag/v3.7.0

Sorry about that.

**Comment by mgorny** [comment]
Thanks!
