### ISSUE TITLE
Difficulty using MergerConfig

### ISSUE THREAD

**Issue by leviem1** [wwkimball/yamlpath#223]
Hey, first off, thanks for the awesome library. This project solves a huge recurring problem for me when trying to parse config files. I plan to use this in a lot of projects moving forward.

From my experience, it seems like this project is CLI-first rather than API-first. This makes the library a huge pain to integrate into other projects. For example, I'm trying to make a CLI program that merges some YAML files, overwriting only specific nodes. It seems like the only way to specify these exceptions using this project is to write out a config file with a list of rules (which in my case changes on every run). This adds unnecessary complexity as I should be able to just pass these options to the `MergerConfig` class directly.

Additionally, the YAML path rules I'm writing into the config include the `:` character, which `ConfigParse` likes to convert to `=`. Then the code in `MergerConfig` assumes that the `=` symbol is part of the value, not the key. I've solve this problem by using the following nasty hack:
```python
        old_init = configparser.ConfigParser.__init__

        def new_init(self):
            old_init(self, delimiters="=")

        configparser.ConfigParser.__init__ = new_init
```

Both of these problems can be solved by allowing rules, defaults, and key to be specified in the class constructor, and only loading from a config file in the event these values are absent.

**Comment by leviem1** [comment]
Btw, I'll have some free-time this weekend. If you agree with my proposal, I can create a PR with the fix for you, but let me know if I should repeat this pattern across all configs or anything else

**Comment by wwkimball** [comment]
Thank you for using this project and offering to contribute!  I genuinely appreciate any and all feedback, good or bad.

I spend considerable time ensuring that every change works equally well for both CLI and library users  This ranges from an extensive collection of tests to spending vast hours on the documentation, both the CLI self-help and [the Wiki](https://github.com/wwkimball/yamlpath/wiki).  However, I can't imagine every possible use-case on my own, so thank you for sharing your frustration with the `MergerConfig` class.

I confess:  I actively use this project in production every day by way of myriad automation (mostly via Jenkins, some cron) as well as one-off manual tasks but I do so via the CLI tools.  As such, you are right; my perspective is indeed CLI-first.

But I recognize that other projects will have different needs than my own.  I'm not a fan of the hack above but if you have other ideas, I'm very interested in exploring them.

By chance, have you seen [the tests for `MergerConfig`](https://github.com/wwkimball/yamlpath/blob/master/tests/test_merger_mergerconfig.py)?  If not, there might be some hints in there you could use to set the configuration via code.

**Comment by leviem1** [comment]
I probably should've explained my solution better. I've looked at your tests, and I've taken the same approach of using a temporary file to write out the rules. It works, but because that file is then parsed by ConfigParser, I get the issue with my delimiters.

If I could just do something like `MergerConfig(logger=logger, rules={"my.yaml.path.with:colons": "left"}, defaults={"aoh", "left"})`, then I wouldn't have to write out a config file for the rules and I wouldn't need my hack just to get `ConfigParser` to skip interpolation on the `:` in my yaml paths.

Alternatively, the ConfigParser instantiation could be moved to `__init__()` so that we can use proper dependency injection, for example `MergerConfig(logger=logger, config_parser=ConfigParser(delimiters="="))`.

**Comment by wwkimball** [comment]
It occurs to me that you are attempting to solve a problem via a CLI tool.  That begs the question:  what are you trying to do that the CLI tools of this project cannot?  I ask because there may be a way without having to write your own.

Would you please add some minimum sample input files with the desired output?

That said, I'd still like to separately work with you on easing access to `MergerConfig`.

**Comment by leviem1** [comment]
What I'm trying to accomplish: Merge a "template" file with a "target" file.

Example template:
```yaml
config:
  aws:region: us-east-2
  aws:insecure: true
```

Example target:
```yaml
config:
  aws:region: eu-west-1
encryptionsalt: v1:abcdefghi=:v1:abc123def456/A9eg:Aojaoifjioajs8y982==
```

Desired outcome:
```yaml
config:
  aws:region: eu-west-1
  aws:insecure: true
encryptionsalt: v1:abcdefghi=:v1:abc123def456/A9eg:Aojaoifjioajs8y982==
```

Additional Requirements:
- From the CLI, be able to optionally specify a list of yaml paths in the "target" file that will be overwritten by the "template" data. Config files don't work for this as these options will change every time the tool is invoked, and editing a config file each time will be cumbersome.
- Search for "template" files from the current working directory up to the root directory.
- Search for "target" files recursively from current working directory through all sub-directories.

**Comment by leviem1** [comment]
I've opened #225 to illustrate my proposed changes. If you agree with my changes, I will add unit tests as needed, just didn't want to spend too long on this in case you disagree.

**Comment by leviem1** [comment]
Thanks again, and I hope things are going better for you. If not now then soon!
