### ISSUE TITLE
Merger API overwrites LHS data

### ISSUE THREAD

**Issue by leviem1** [wwkimball/yamlpath#226]
## Operating System

1. Name/Distribution: macOS
2. Version: Sonoma 14.0

## Version of Python and packages in use at the time of the issue.

1. [Distribution](https://wiki.python.org/moin/PythonDistributions): CPython
2. Python Version: 3.12.0
3. Version of yamlpath installed: 3.8.1
4. Version of ruamel.yaml installed: 0.17.21

## Minimum sample of YAML (or compatible) data necessary to trigger the issue
lhs_data:
```yaml
a: 1
```

rhs_data:
```yaml
b: 2
```

## Complete steps to reproduce the issue when triggered via Library:
```python
lhs_data = ... # Load from Parsers.get_yaml_data()
rhs_data = ... # Load from Parsers.get_yaml_data()

log = ConsolePrinter(SimpleNamespace(quiet=True, verbose=True, debug=True))
merger = Merger(
    log,
    lhs_data,
    MergerConfig(
        logger=log,
        args=argparse.Namespace(config=tf.name),
    ),
)
merger.merge_with(rhs_data)
merger.prepare_for_dump(Parsers.get_yaml_editor(), "out.yaml")
output = merger.data
```

## Expected Outcome
Library should not mutate LHS data.
```python
lhs == {"a": 1}
rhs == {"b": 2}
output == {"a": 1, "b": 2}
```

## Actual Outcome
Library mutates LHS data.
```python
lhs == {"a": 1, "b": 2}
rhs == {"b": 2}
output == {"a": 1, "b": 2}
```

## Screenshot(s), if Available
N/a

**Comment by leviem1** [comment]
I was able to work around this issue in my code by creating the following function:
```python
def copy_data(data: Any, yaml: YAML) -> Any:
    buf = io.BytesIO()
    yaml.dump(data, buf)
    buf.flush()
    buf.seek(0)
    return yaml.load(buf)
```

Which I've used as follows:
```python
merger = Merger(
    log,
    copy_data(lhs_data, yaml),
    MergerConfig(
        logger=log,
        args=argparse.Namespace(config=tf.name),
    ),
)
```

I'd still prefer that my `lhs_data` not be mutated, especially because this make the `Merger.data` attribute redundant IMO, but I understand implementing a change like this would cause breaking changes due to the requirement of the YAML instance. I don't think there's a simple solution for this.

Nonetheless, I think my workaround might be helpful for new users encountering this behavior for the first time.

**Comment by wwkimball** [comment]
The described behavior is as designed and [covered in the documentation](https://github.com/wwkimball/yamlpath/wiki/merger.py).  When you need to preserve a copy of the LHS document, it is up to you to do so before wrapping the document with the `Merger`.
