### ISSUE TITLE
[request] remove dateutil dependency

### ISSUE THREAD

**Issue by sigma67** [wwkimball/yamlpath#227]
**Is your feature request related to a problem? Please describe.**

The dateutil dependency has had its last release in 2021 and struggled to keep up with latest Python release, causing DeprecationWarnings in all packages that (transitively) use it. 

In addition, `yamlpath` only depends on it to parse timestamps, which should be achievable without it.

**Describe the solution you'd like**
A native solution to parse timestamps

**Describe alternatives you've considered**
None

**Additional context**
[Add any other context or screenshots about the feature request here.](https://github.com/dateutil/dateutil/issues/1314)

**Comment by wwkimball** [comment]
Date/time parsing is not as simple as it may seem given nontrivial differences in localization and presentation, hence my decision to use an established library for this purpose.  The master branch of dateutil shows recent activity, so I'm going assume they are working (albeit slowly) on another release.  For now, I'm going to close this as a non-issue.  Should the "warning" ever become an "error", let's look for a replacement.

**Comment by AndydeCleyre** [comment]
I'll note here that two very popular high level date handler libraries, pendulum and arrow, continue to depend on dateutil as well.
